#undef DEFGRAMMAR
#undef DEFBASICNODE
#undef ENDBASICNODE
#undef ENDGRAMMAR
#undef DEFRULE
#undef BEGINRULE
#undef ENDRULE
#undef DEFRULES
#undef ENDRULES
#undef EXPECT
#undef TX
#undef COMMIT
#undef ROLLBACK
#undef ASTERISK
#undef OR
#undef OR3
#undef OR4
#undef OR5
#undef OR6
#undef MAYBE
#undef DEFTOKENS
#undef ENDTOKENS
#undef DEFTOKEN
#undef ENDTOKEN
#undef MAINRULE
#undef RULE
#undef TOKEN
#undef DEFNODE
#undef ENDNODE
